package fr.inria.ilda.gestures;

public enum GestureControl {
	ZOOM_IN,
	ZOOM_OUT,
	SCALE_SELECTION_NORTH,
	SCALE_SELECTION_SOUTH,
	SCALE_SELECTION_WEST,
	SCALE_SELECTION_EAST,
	NEXT_COLOR_MAPPING,
	PREV_COLOR_MAPPING,
//	PAN,
	NONE
}
